#!/bin/bash
# Test Execution Script for EduAssist-AI-FE

echo "=========================================="
echo "EduAssist-AI-FE Selenium Test Suite"
echo "=========================================="
echo ""
echo "This script runs the complete Selenium test suite for the EduAssist-AI-FE application."
echo ""

echo "Available Test Commands:"
echo "1. Run all tests:"
echo "   python -m pytest tests/tests/ -v"
echo ""
echo "2. Run tests in headless mode (recommended for CI):"
echo "   HEADLESS=true python -m pytest tests/tests/ -v"
echo ""
echo "3. Run specific test files:"
echo "   HEADLESS=true python -m pytest tests/tests/test_user_registration_login.py -v"
echo "   HEADLESS=true python -m pytest tests/tests/test_basic_navigation.py -v"
echo "   HEADLESS=true python -m pytest tests/tests/test_application_health.py -v"
echo ""
echo "4. Run with HTML report:"
echo "   HEADLESS=true python -m pytest tests/tests/ -v --html=reports/test_report.html --self-contained-html"
echo ""
echo "Prerequisites:"
echo "- Chrome browser must be installed"
echo "- ChromeDriver should be in PATH (or webdriver-manager will download automatically)"
echo "- The EduAssist-AI-FE application must be running on http://localhost:5173"
echo ""
echo "Test Suite Includes:"
echo "- Basic navigation tests"
echo "- User registration (with faculty checkbox)"
echo "- User login functionality"
echo "- Application health checks"
echo "- Route accessibility verification"
echo ""
echo "To run the complete test suite, execute:"
echo "npm run dev  # In another terminal to start the application"
echo "set HEADLESS=true && python -m pytest tests/tests/ -v"
echo ""